[google_oauth]
client_id = "SEU_CLIENT_ID"
client_secret = "SEU_CLIENT_SECRET"
project_id = "SEU_PROJECT_ID"

[google_token]
refresh_token = "SEU_REFRESH_TOKEN"
token_uri = "https://oauth2.googleapis.com/token"
scopes = [
  "https://www.googleapis.com/auth/drive",
  "https://www.googleapis.com/auth/spreadsheets"
]

[google_drive]
folder_id = "ID_DA_PASTA_NO_GOOGLE_DRIVE"

[manager]
password = "DEFINA_SUA_SENHA_DO_GESTOR"

[google_maps]
api_key = "SUA_GOOGLE_MAPS_API_KEY_OPCIONAL"
